version: '3.1'

services:
  mysqldb:
    image: mysql:8.0.32
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: microservice
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
